FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI += "file://0001-arm64-dts-imx8mm-evk-harpoon-imx8mn-evk-harpoon-imx8.patch"
SRC_URI += "file://0002-arm64-dts-imx8mm-evk-harpoon-remove-sai5.patch"
SRC_URI += "file://0003-arm64-dts-imx8mp-evk-harpoon-Enable-SAI-audio-case-i.patch"
SRC_URI += "file://0004-arm64-dts-imx8mn-evk-harpoon-Enable-SAI-audio-case-i.patch"
SRC_URI += "file://0005-arm64-dts-imx8m-m-n-p-evk-harpoon-Remove-iomux-setti.patch"
SRC_URI += "file://0006-arm64-dts-imx8m-m-n-p-evk-harpoon-disable-all-SAIs.patch"
SRC_URI += "file://0007-arm64-dts-imx8m-m-n-p-evk-Create-DTS-file-for-indust.patch"
SRC_URI += "file://0008-arm64-dts-imx8m-m-n-p-evk-Build-DTB-file-for-industr.patch"
SRC_URI += "file://0009-arm64-dts-imx8mn-evk-root-disable-busfreq.patch"
SRC_URI += "file://0010-arm64-dts-imx8m-m-n-p-evk-Add-DTS-file-for-audio-AVB.patch"
SRC_URI += "file://0011-arm64-dts-imx8m-add-SGI-mailbox-dtsi-file.patch"
SRC_URI += "file://0012-arm64-dts-imx8mm-add-Cortex-A53-RPMSG-dtsi-file.patch"
SRC_URI += "file://0013-arm64-dts-imx8mm-include-Cortex-A53-RPMSG-dtsi-in-ha.patch"
SRC_URI += "file://0014-rpmsg-Kconfig-remove-the-selection-of-the-RPMSG_VIRT.patch"
