# Copyright 2022, 2024-2025 NXP

BOARD:imx8mm-lpddr4-evk = "imx8mm_evk/mimx8mm6/a53"
BOARD:imx8mn-lpddr4-evk = "imx8mn_evk/mimx8mn6/a53"
BOARD:imx8mp-lpddr4-evk = "imx8mp_evk/mimx8ml8/a53"
BOARD:imx93evk = "imx93_evk/mimx9352/a55"
BOARD:imx943-19x19-lpddr5-evk = "imx943_evk/mimx94398/a55"
BOARD:imx95-15x15-lpddr4x-evk = "imx95_evk_15x15/mimx9596/a55"
BOARD:imx95-19x19-lpddr5-evk = "imx95_evk/mimx9596/a55"
